# Admin companies

winter-solstice-description = All three branches of the Trans-Solar Marines Federation fall under the direction of the Federation's unified high command, known as Winter Solstice.


# Core companies

drake-industries-description = Titan of the trade routes & Core company. What started of as a small transport fleet quickly became the lead in bulk transport & refining within the boundaries of the Colossus sector. Owning a monopoly in these domains allowed this corporation to grow exponentially amidst the high tensions in the sector and trade with all major groups without bias. The exclusive, hyper optimised ship-set it brought upon the market as part of it's expansion is highly prized for freelancers & corporation traders alike, despite the lack of comfort. Officially, it discourages any kind of hostilities performed by the members of the company. It promises easy profits to all capable pilots, traders & private securities who wish to apply. Don't act surprised when the working conditions are composed of throat-cutting deadlines, no bathroom breaks & sleeping on a dirty bedroll, though.

steel-hammer-description = Massive industrial conglomerate, and Core Company. Specializes in the designing, construction, and outfitting of starship hulls employed by civilians, PMCs, or the highest bidder, utilizing grassroots startups, established industrial trade allies, and outsourced independent systems engineers. Key supplier of hulls and outfitted ships to the Colossus sector, making it one of the swords of the brewing conflict between the major factions vying for dominance. After the historical collapse of the Nanotrasen megacorporation and the Syndicate Allies, surviving profit-motivated hull manufacturing subsidiaries from both sides realized the best course of action was to separate as best they could from the destroyed powers and start anew. SHM accepts blueprints from all sorts of independent (or not) designers for all kinds of reasons, from improving the roster of universally available hulls on the intergalactic market, to… extremely valuable factional contracts. **Members of Steel Hammer Manufacturing are usually ship makers, breakers, designers, or maintainers.**

harmony-medical-enterprises-description = Harmony Medical Enterprises is a corporation based solely within medical practices and supplies, when you get hit in the battlefield? HME is the one that's provided your higher-ups with a discount deal on combat pens and various meds that keep you in the fight for longer. Harmony Medical Enterprises are the primary manufacturers that push things like medkits, combat pens, medipen cases, medical equipment, all of the lifesaving technology into the sector. While they have no dominion over cloning? They have the next best thing, medicine for the living.

midnight-arms-co-description = Midnight Arms Company took advantage of a recently remade galaxy, one that lacked and forbid mega-corporations in all capacities. Midnight Arms provides independent masses and various other corporations armaments for whatever they need them for, what they are used for, well that is up to those that buy them. Guns are needed for all things in this age, self defense, expeditions, bounty hunting. All are jobs that need weapons to carry them out, MACo just finds itself to be the primary provider.


# Major companies

dark-matter-enterprises-description = A corporate conglomerate of mercenaries, scientists, physicians, engineers, merchants, contractors, and clowns all of which vary in qualifications, if any. Founded by unhinged ex-Nanotrasen Contractors, DME operates with one goal in mind: Profit. All members of the DME operate towards maximizing profit margins, for themselves alongside subsidiaries under the organization. DME functions under one core tenant called the Golden Rule which states “No infighting between enterprise members as this negatively affects profit margins.”

aetherion-dynamics-description = Representing the forefront of technological innovation, Aetherion Dynamics is renowned for their invention of the Compressed Gas Launch and Projectile (CGLP) system used in the ADEX-9 Dymere turbolaser battery, and additional innovative weapons with little to no consistent design philosophy. Between all of their famous ship guns, they began the Gunnery Revolution in the buildup to the conflict in Colossus Sector. They have a reputation as high quality manufacturers and designers, more interested in building an effective product than on making a profit.

horizon-energy-description = The lead in gas extraction, from the monolith's valuable Prismatic Plasma, to the gas filled asteroids of the outer rim in the Colossus sector. They are the current industry leaders when it comes to the atmospherics extraction & engineering field.  They provide services useful for both new and enterprising miners, to the veteran and experienced gassers alike. Chances are, the air the regular spacer breathes and gas trail their ship leaves behind came from Horizon Energy.


# Minor companies

universal-states-of-america-description = The Universal States of America is a group of fanatical mercenaries that wish to bring the values of the ancient United States to the 25th century. They practically function as a PMC group, outsourcing patriotic militiamen as mercenaries, under the name 'Vanguards' to fund their dreams of creating a vast and powerful nation akin to the U.S.A, a dream in which they will most likely never fulfill. But, in their eyes, logic and common sense are no match for freedom. Exercise your right to the Second Amendment, scream at a chef because he calls his fries Space Fries instead of Freedom Fries, and make it known that you are a gun-lovin', weak-defendin', burger eatin', space truckin', Universal frickin' patriot! 

civil-defense-milita-description = A fairly new company founded within the Colossus Sector, the Civil Defense Militia was formed to protect the civilian populace and its interests. Answering to high ranking individuals decided through their reputation, the militia partakes in acts of selflessness such as defending major points of interests and maintaining ceasefires so that civilians may safely partake in trade among the system. The C.D.M. consists of volunteer contractors and mercenaries and have access only to the equipment available to them. For the people. Defend and partake not in senseless acts of violence. You are the defender of those who cannot defend themselves.

southern-peak-mercenaries-description = “A good rogue is a dead rogue.” says the slogan of this vicious mercenary company. The Southern Peaks were formed along the TSF-Rogue space border out retaliation against encroaching pirates and insurgents in combination with a sheer distrust of the TSFMC. Without the need of any other organization, TSP aims to fight back the Rogue Sector on its own.

ullman-industries-description = It's not a warcrime the first time. Originally a staple company in the lawless sector for small arms production and pharmaceuticals, once the TSF arrived, most companies went public sector- registering and abiding "safe work practices" and paying employees a "living wage"- as well as pursuing company leaders for charges of "war crimes". Ullman Industries broke this trend by staying true to their roots as a fringe element, supplying arms, armor, ships, you name it to any and all customers in the Ashen Republic. Bottom line is- if it's illegal in Federation space, it's probably sold by Ullman Industries. Hell, they're probably the ones who built it.

nosske-eien-rnd-description = Renowned in other sectors for their cutting edge technology and advancements, Nosske-Eien had began branching out and dipping their toes in the Rogue sector by contracting local workforce, be it regular civilians, pilots or mercenaries, for the research regarding the local xenoarchaeology, xenobiology and technological advancements. Nosske-Eien has been the primary source for the recent science technological advancements and equipment, as well as high-tech asteroid mining equipment and soon, shuttlecraft. Though, there are rumours of their contractors randomly disappearing from time to time, let's hope it's just a ruse and nothing to worry about, huh?

blackhawkpmc-description = The Blackhawk Military Contracting group (BMC) is a premium mercenary group operating in the Colossus sector. Mercenaries in the group are expected to be trained and professional. They perform mercenary tasks ranging from asset protection to assassination whilst upholding their reputation. The group is fairly new, created by a group of independent mercenaries looking to build a powerful mercenary group. As of now, recruitment operations are on the rise. Blackhawk PMC offers a range of services, from providing private security to full assasinations. Blackhawk mercenaries wear green and often avoid drawing attention to themselves. Fight anyone for anything to make money.


# Religious groups

zealots-of-balaam-description = The Zealots and pilgrims of Balaam are luddites with a extreme aversion to the use of Hi-tech. They are overtly isolationist, preferring to raid convoys that move too far into space. As a follower of the blessed god, work underneath a senior zealot to help them levy their tithes. Never listen to the blasphemy of the other companies. Kill those who profane Balaam's eye with the use of shield tech and FTL, heavy industry is not safe either.

cult-of-the-machine-god-description = The flesh is weak. To walk the path of the Cult of the Machine God is to reject the chaos of flesh and embrace the divine order of logic. The faithful act with precision and purpose, never swayed by emotion or impulse. Advancement comes not through passion, but through calculated improvement and unwavering discipline. Those who command in the Cult do so through algorithmic clarity, deploying Ascended operatives with mechanical efficiency and spreading influence through hidden Devotees or roaming Vessels led by Techpriests. Whether enforcing doctrine in distant sectors or executing cold, strategic dominion, every action must serve the grand equation. In all things, reason must rule, and through it, the Machine God's will is made manifest...


# Hostile/rogue affiliated companies

viper-group-description = Formerly a privateering company domineered by military discipline with the sole mission of intercepting, disrupting and confiscating through TSF shipping routes along the fringes of USSP-TSF space in Sector 2. The Viper Group (VG) abruptly switched allegiances after a substantial number of tragic events in series. The TSF had offered the former-USSP backed organization substantial payment for subterfuge operations against the USSP, only to reveal them to the USSP soon after. Driven away by false bribes and murderous betrayal, TVG leadership was left to fester; often violently switching hands until “greed is good” eventually became the unspoken oath of membership. equitable relations with the Rogue Sector quickly expedited their arrival to rogue space. If you yearn for danger and wealth, join The Viper Group!