using Content.Client.Computer;
using Content.Client.UserInterface.Controls;
using Robust.Client.UserInterface.Controls; // Mono
using Content.Shared.Shuttles.BUIStates;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Map;

namespace Content.Client.Shuttles.UI;

[GenerateTypedNameReferences]
public sealed partial class RadarConsoleWindow : FancyWindow,
    IComputerWindow<NavInterfaceState>
{
    public RadarConsoleWindow()
    {
        RobustXamlLoader.Load(this);

    // Mono
        IFFToggle.OnToggled += OnIFFTogglePressed;
        IFFDetailedToggle.OnToggled += OnIFFDetailedTogglePressed;
    }

    public void UpdateState(NavInterfaceState scc)
    {
        RadarScreen.UpdateState(scc);
    }

    public void SetConsole(EntityUid consoleEntity)
    {
        RadarScreen.SetConsole(consoleEntity);
    }

    // Mono
    private void OnIFFTogglePressed(BaseButton.ButtonEventArgs args)
    {
        RadarScreen.ShowIFF ^= true;
        args.Button.Pressed = RadarScreen.ShowIFF;
    }

    // Mono
    private void OnIFFDetailedTogglePressed(BaseButton.ButtonEventArgs args)
    {
        RadarScreen.ShowIFFDetailed ^= true;
        args.Button.Pressed = RadarScreen.ShowIFFDetailed;
    }
}

