# USSP
- type: playTimeTracker
  id: JobUSSPCommissar

- type: playTimeTracker
  id: JobUSSPRifleman

- type: playTimeTracker
  id: JobUSSPSergeant

# MD for some reason

- type: playTimeTracker
  id: MdMedic

# Vipergroupo
- type: playTimeTracker
  id: JobVGInfanteer

- type: playTimeTracker
  id: JobVGLieutenant

- type: playTimeTracker
  id: JobVGCommander

# PDV
- type: playTimeTracker
  id: JobPDVTarkhan

- type: playTimeTracker
  id: JobPdvBorg

- type: playTimeTracker
  id: JobPDVAsvaran

- type: playTimeTracker
  id: JobPDVGrandVizier

- type: playTimeTracker
  id: JobPDVDenasvar

- type: playTimeTracker
  id: JobPDVRahkshan

- type: playTimeTracker
  id: JobPDVInfiltrator


#TSF
- type: playTimeTracker
  id: JobTsfMarsoc

- type: playTimeTracker
  id: JobTsfEngineer

- type: playTimeTracker
  id: JobTsfBorg

- type: playTimeTracker
  id: JobTsfOfficer

- type: playTimeTracker
  id: JobTsfTeamleader

- type: playTimeTracker
  id: JobTsfCommander

- type: playTimeTracker
  id: JobTsfCorpsman

- type: playTimeTracker
  id: JobTsfMarine

- type: playTimeTracker
  id: JobTsfRecruit

- type: playTimeTracker
  id: JobMMCEmployee

- type: playTimeTracker
  id: JobMMCSecurity

- type: playTimeTracker
  id: JobMMCLiason
