- type: job
  id: Contractor
  name: job-name-contractor
  description: job-description-contractor
  playTimeTracker: JobPassenger
#  requirements: # If a new player decides the role named vagrant is better for guidance than employee/citizen it's their fault
#  - !type:OverallPlaytimeRequirement
#    time: 43200 # 12 hours
  icon: "JobIconContractor"
  supervisors: job-supervisors-nobody
  displayWeight: 40 # Top
  accessGroups: # Frontier
  - GeneralAccess # Frontier
  special:
  - !type:GiveItemOnHolidaySpecial
    holiday: FrontierBirthday
    prototype: FrontierBirthdayGift
