- type: job
  id: TsfCorpsman
  name: job-name-tsf-corpsman
  description: job-description-tsf-corpsman
  playTimeTracker: JobTsfCorpsman
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 72000 # 20 hours - mono
    - !type:DepartmentTimeRequirement
      department: Tsf
      time: 18000 # 5 hours - mono
  alternateRequirementSets:
    longerPlaytimeLessSec:
    - !type:DepartmentTimeRequirement
      department: Security #old tsf department name
      time: 18000 # 5 hours - mono
    - !type:OverallPlaytimeRequirement
      time: 72000 # 20 hours - mono
  startingGear: TsfCorpsmanGear
  icon: JobIconTSFCorpsman
  supervisors: job-supervisors-tsf
  weight: 125
  displayWeight: 35
  assignedCompany: TSF
  canBeAntag: false
  access:
  - TsfGeneral
  - Medical
  - Chemistry
  accessGroups:
  - GeneralAccess
  special:
  - !type:AddComponentSpecial
    components:
    - type: NpcFactionMember
      factions:
      - TSFMC
    - type: SurgerySpeedModifier
      SpeedModifier: 1.65
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, TrackingImplant ]
  - !type:AddLanguageSpecial # Monolith - Languages
    languagesSpoken:
    - SolCommon
    languagesUnderstood:
    - SolCommon
  - !type:GiveItemOnHolidaySpecial
    holiday: FrontierBirthday
    prototype: FrontierBirthdayGift

- type: startingGear
  id: TsfCorpsmanGear
#  equipment:
#    pocket1: WeaponPistolMk58 #WeaponPistolMk58Nonlethal
  storage:
    back:
    - EncryptionKeyMedical
#    - Magazine45_ACPPistolFMJ # Mono
    - BaseTSFUplinkRadioTeamleader #Mono: Changed to officer uplink
    - RadioHandheldNF # Mono
