- type: job
  id: TsfEngineer
  name: job-name-tsf-engineer
  description: job-description-tsf-engineer
  playTimeTracker: JobTsfEngineer
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 54000 # 15 hours # mono #fuck this engineers aren't supposed to be the newbuddies
    - !type:DepartmentTimeRequirement
      department: Tsf
      time: 18000 # 5 hours - mono
  alternateRequirementSets:
    longerPlaytimeLessSec:
    - !type:DepartmentTimeRequirement
      department: Security #old tsf department id
      time: 18000 # 5 hours - mono
  startingGear: TsfEngiGear
  icon: JobIconTSFEngi
  supervisors: job-supervisors-tsf-teamleader
  weight: 130
  displayWeight: 20
  assignedCompany: TSF
  canBeAntag: false
  access:
  - TsfmcEngineering
  - TsfGeneral
  - TsfFtl
  accessGroups:
  - GeneralAccess
  special:
  - !type:AddComponentSpecial
    components:
    - type: NpcFactionMember
      factions:
      - TSFMC
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, TrackingImplant ]
  - !type:AddLanguageSpecial
    languagesSpoken:
    - SolCommon
    languagesUnderstood:
    - SolCommon
  - !type:GiveItemOnHolidaySpecial
    holiday: FrontierBirthday
    prototype: FrontierBirthdayGift

- type: startingGear
  id: TsfEngiGear
#  equipment:
#    pocket1: WeaponPistolMk58 #WeaponPistolMk58Nonlethal
#    pocket2: Magazine45_ACPPistolFMJ
  storage:
    back:
    - RadioHandheldNF
    - NanolaminateFoamGrenade
    - NanolaminateFoamGrenade
    - RCDRecharging
    - NFPouchUtility
