- type: job
  id: TsfMarine
  name: job-name-tsf-marine
  description: job-description-tsf-marine
  playTimeTracker: JobTsfMarine
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 36000 # 10 hours
  startingGear: TsfMarineGear
  icon: JobIconTSFMarine
  supervisors: job-supervisors-tsf
  weight: 130
  displayWeight: 40
  assignedCompany: TSF
  canBeAntag: false
  access:
  - TsfGeneral
  accessGroups:
  - GeneralAccess
  special:
  - !type:AddComponentSpecial
    components:
    - type: NpcFactionMember
      factions:
      - TSFMC
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, TrackingImplant ]
  - !type:AddLanguageSpecial # Monolith - Languages
    languagesSpoken:
    - SolCommon
    languagesUnderstood:
    - SolCommon
  - !type:GiveItemOnHolidaySpecial
    holiday: FrontierBirthday
    prototype: FrontierBirthdayGift

- type: startingGear
  id: TsfMarineGear
#  equipment:
#    pocket1: WeaponPistolMk58 #WeaponPistolMk58Nonlethal
  storage:
    back:
#    - Magazine45_ACPPistolFMJ  Mono
    - BaseTSFUplinkRadioMarine #Mono: Added Deputy uplink
    - RadioHandheldNF # Mono
