- type: job
  id: TsfOfficer
  name: job-name-tsf-officer
  description: job-description-tsf-officer
  playTimeTracker: JobTsfOfficer
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 180000 # 50 hours
    - !type:RoleTimeRequirement
      role: JobTsfTeamleader
      time: 28800 # 8 hours
  alternateRequirementSets:
    longerPlaytimeLessSec:
    - !type:OverallPlaytimeRequirement
      time: 180000 # 50 hours
    - !type:RoleTimeRequirement
      role: JobSeniorOfficer #old teamleader id
      time: 28800
  startingGear: TsfOfficerGear
  icon: JobIconTSFOfficer
  supervisors: job-supervisors-tsf-officer
  weight: 150
  displayWeight: 60
  assignedCompany: TSF
  canBeAntag: false
  access:
  - TsfOfficer
  - TsfGeneral
  - TsfmcEngineering
  - TsfFtl
  - TsfmcEngineering # Mono
  accessGroups:
  - GeneralAccess
  special:
  - !type:AddComponentSpecial
    components:
    - type: NpcFactionMember
      factions:
      - TSFMC
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, TrackingImplant ]
  - !type:AddLanguageSpecial
    languagesSpoken:
    - SolCommon
    languagesUnderstood:
    - SolCommon
  - !type:GiveItemOnHolidaySpecial
    holiday: FrontierBirthday
    prototype: FrontierBirthdayGift

- type: startingGear
  id: TsfOfficerGear
#  equipment:
#    pocket1: WeaponPistolMk58 #WeaponPistolMk58Nonlethal
  storage:
    back:
#    - Magazine45_ACPPistolFMJ # Mono
    - BaseTSFUplinkRadioOfficer
#    - ShipVoucherNfsdBailiff # Mono
    - RadioHandheldNF # Mono
    - RubberStampTSFCaptain # Mono
