- type: job
  id: TsfTeamleader
  name: job-name-tsf-teamleader
  description: job-description-tsf-teamleader
  playTimeTracker: JobTsfTeamleader
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 72000 # 20 hours # mono
    - !type:DepartmentTimeRequirement
      department: Tsf
      time: 36000 # 10 hours # mono
  alternateRequirementSets:
    longerPlaytimeLessSec:
    - !type:DepartmentTimeRequirement
      department: Security #old tsf department id -nuke when needed no more
      time: 36000 # 10 hours - mono
  startingGear: TsfTeamleaderGear
  icon: JobIconTsfTeamLeader
  supervisors: job-supervisors-tsf-teamleader
  weight: 140
  displayWeight: 50
  assignedCompany: TSF
  canBeAntag: false
  access:
  - TsfGeneral
  - TsfFtl
  - TsfmcEngineering
  accessGroups:
  - GeneralAccess
  special:
  - !type:AddComponentSpecial
    components:
    - type: NpcFactionMember
      factions:
      - TSFMC
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, TrackingImplant ]
  - !type:AddLanguageSpecial # Monolith - Languages
    languagesSpoken:
    - SolCommon
    languagesUnderstood:
    - SolCommon
  - !type:GiveItemOnHolidaySpecial
    holiday: FrontierBirthday
    prototype: FrontierBirthdayGift

- type: startingGear
  id: TsfTeamleaderGear
#  equipment:
#    pocket1: WeaponPistolMk58 #WeaponPistolMk58Nonlethal
  storage:
    back:
#    - Magazine45_ACPPistolFMJ Mono
    - BaseTSFUplinkRadioTeamleader
#    - ShipVoucherNfsdSergeant # Mono
    - RadioHandheldNF # Mono
