- type: job
  id: Godfather
  name: job-name-godfather
  description: job-description-godfather
  playTimeTracker: JobGodfather
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 54000 # 15 hours # mono
  - !type:RoleTimeRequirement
    role: JobFugitive
    time: 18000 # 5 hours
  whitelisted: true # I am NOT trusting regular players to not just use this role to frag out.
  startingGear: GodfatherGear
  icon: JobIconGodfather
  alwaysUseSpawner: true
  supervisors: job-supervisors-nobody
  displayWeight: 150
  accessGroups:
  - GeneralAccess
  access: 
  - Underground
  - Godfather
  special:
  - !type:GiveItemOnHolidaySpecial
    holiday: FrontierBirthday
    prototype: FrontierBirthdayGift
  - !type:AddComponentSpecial
    components:
    - type: Contraband
      hideValues: true
      turnInValues:
        FederationMilitaryCredit: 400 # bounty on your head
    - type: RadioOnCryosleep
      radioChannel: Syndicate # Syndicate = Underground
  - !type:AddImplantSpecial
    implants: [ DeathRattleImplant, RadioImplant ]

- type: startingGear
  id: GodfatherGear
  equipment:
    pocket1: WeaponPistolDamocles
    pocket2: EnergySword
  storage:
    back:
    - Telecrystal50 # 50 TC
    - Magazine9x19mmPistolHighCapacityFMJ
    - Magazine9x19mmPistolHighCapacityFMJ
    - ContractorIDCard
