- type: job
  id: PDVAsvaran
  name: job-name-pdv-asvaran
  description: job-description-pdv-asvaran
  playTimeTracker: JobPDVAsvaran
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 180000 # 50 hours # mono
    - !type:RoleTimeRequirement
      role: JobPDVDenasvar
      time: 28800 # 8 hours
  startingGear: PDVAsvaranGear
  alwaysUseSpawner: true
  hideConsoleVisibility: true
  canBeAntag: true
  icon: "JobIconPDVAsvaran"
  supervisors: job-supervisors-pdv-asvaran
  weight: 40
  displayWeight: 40
  assignedCompany: PDV
  setPreference: true
  access:
  - PDVGeneral
  - PDVCommand
  - Mercenary
  accessGroups:
  - GeneralAccess
  special:
  - !type:AddComponentSpecial
    components:
    - type: NpcFactionMember
      factions:
      - PirateNF
    - type: ChatRank
      rank: pdv-asvaran
  - !type:AddImplantSpecial
    implants: [ FreelanceTrackingImplant ]
  - !type:AddLanguageSpecial # Monolith - Languages
    languagesSpoken:
    - Freespeak
    languagesUnderstood:
    - Freespeak
  - !type:GiveItemOnHolidaySpecial # Even pirates get a piece of cake.
    holiday: FrontierBirthday
    prototype: FrontierBirthdayGift

- type: startingGear
  id: PDVAsvaranGear
  equipment:
    ears: ClothingHeadsetAltVanguardCommand
    #belt: ClothingBeltUtility
    pocket1: BasePDVUplinkAsvaran
    #pocket2: AppraisalTool
  storage:
    back:
    - RadioHandheldNF
    - RubberStampPDVAsvaran # mono
