- type: job
  id: PDVGrandVizier
  name: job-name-pdv-vizier
  description: job-description-pirate-captain
  playTimeTracker: JobPDVGrandVizier
  requirements:
    - !type:OverallPlaytimeRequirement # mono start
      time: 144000 # 40 hours
    - !type:RoleTimeRequirement
      role: JobPDVAsvaran
      time: 18000 # 5 hours - mono
  alternateRequirementSets:
    longerPlaytimeLessSec:
    - !type:OverallPlaytimeRequirement
      time: 144000 # 20 hours # mono
    - !type:RoleTimeRequirement
      role: JobPirateFirstMate
      time: 18000 # 5 hours - mono
  whitelisted: true
  startingGear: PDVGrandVizierGear
  alwaysUseSpawner: true
  hideConsoleVisibility: true
  canBeAntag: true
  icon: "JobIconPDVGrandVizier"
  supervisors: job-supervisors-nobody
  weight: 50
  displayWeight: 50
  assignedCompany: PDV
  setPreference: true
  access:
  - PDVGeneral
  - GrandVizier
  - PDVCommand
  - Mercenary
  accessGroups:
  - GeneralAccess
  special:
  - !type:AddComponentSpecial
    components:
    - type: NpcFactionMember
      factions:
      - PirateNF
    - type: ChatRank
      rank: pdv-vizier
  - !type:AddImplantSpecial
    implants: [ FreelanceTrackingImplant ]
  - !type:AddLanguageSpecial # Monolith - Languages
    languagesSpoken:
    - Freespeak
    languagesUnderstood:
    - Freespeak
  - !type:GiveItemOnHolidaySpecial # Even pirates get a piece of cake.
    holiday: FrontierBirthday
    prototype: FrontierBirthdayGift

- type: startingGear
  id: PDVGrandVizierGear
  equipment:
    ears: ClothingHeadsetAltVanguardCommand
    #belt: ClothingBeltUtility # mono
    pocket1: BasePDVUplinkRadioPDVGrandVizier
    pocket2: EnergySword
  storage:
    back:
    - RadioHandheldNF # mono
    - PhoneInstrumentHigh
    - RubberStampPDVVizier # mono
    - PDVHandheldOverwatchConsole
