- type: job
  id: CrocusDockworker
  name: job-name-crocus-dockworker
  description: job-description-crocus-dockworker
  playTimeTracker: JobCrocusDockworker
  startingGear: JianghuiDockworkerGear
  alwaysUseSpawner: true
  hideConsoleVisibility: true
  icon: "JobIconStationEngineer"
  supervisors: job-supervisors-nobody
  assignedCompany: MMC
  canBeAntag: false
  setPreference: false
  weight: 10
  displayWeight: 10
  accessGroups:
  - GeneralAccess
  special:
  - !type:AddLanguageSpecial
    languagesSpoken:
    - NovuNederic
    languagesUnderstood:
    - NovuNederic
    # TRUST
    removeLanguagesSpoken:
    - TauCetiBasic
    removeLanguagesUnderstood:
    - TauCetiBasic

- type: startingGear
  id: JianghuiDockworkerGear
  equipment:
    belt: ClothingBeltSalvageWebbingFilledNF
    shoes: ClothingShoesBootsWork
    jumpsuit: ClothingUniformJumpsuitMilitaryContractor
    outerClothing: ClothingOuterVestHazard
    gloves: ClothingHandsGlovesColorYellowBudget
    head: ClothingHeadHatCorpsoft
    pocket1: RadioHandheldNF
    pocket2: FlashlightLantern
