- type: job
  id: PDVAmbassador
  name: job-name-pdv-ambassador
  description: job-description-pdv-ambassador
  playTimeTracker: JobPDVAmbassador
  startingGear: PDVAmbassadorGearEvent
  icon: JobIconPDVAmbassador
  supervisors: job-supervisors-nobody
  weight: 0
  displayWeight: 0
  assignedCompany: PDV
  canBeAntag: false
  setPreference: true
  access:
  - Pirate
  - GrandVizier
  - PDVCommand
  - Mercenary
  accessGroups:
  - GeneralAccess
  special:
  - !type:AddComponentSpecial
    components:
    - type: NpcFactionMember
      factions:
      - PirateNF
  - !type:AddImplantSpecial
    implants: [ FreelanceTrackingImplant ]
  - !type:AddLanguageSpecial
    languagesSpoken:
    - Freespeak
    languagesUnderstood:
    - Freespeak
