using System.Linq;
using System.Text;
using Content.Client.Materials;
using Content.Client.Storage.Components;
using Content.Client.Stylesheets; // Mono
using Content.Shared.Lathe;
using Content.Shared.Lathe.Prototypes;
using Content.Shared.Research.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Content.Client.UserInterface.Controls;
using Content.Shared.Chemistry.EntitySystems;
using Content.Shared.Chemistry.Reagent;
using Content.Shared.FixedPoint;
using Content.Shared.Stacks;
using Content.Shared.Storage.EntitySystems;
using Robust.Shared.Containers;

namespace Content.Client.Lathe.UI;

[GenerateTypedNameReferences]
public sealed partial class LatheMenu : FancyWindow
{
    [Dependency] private IEntityManager _entityManager = default!;
    [Dependency] private IPrototypeManager _prototypeManager = default!;

    private readonly SpriteSystem _spriteSystem;
    private readonly LatheSystem _lathe;
    private readonly MaterialStorageSystem _materialStorage;
    private readonly SharedContainerSystem _container; // mono
    private readonly SharedSolutionContainerSystem _solution; // mono


    public event Action<BaseButton.ButtonEventArgs>? OnServerListButtonPressed;
    public event Action<string, int>? RecipeQueueAction;
    // <Mono>
    public event Action<bool>? OnLoopCheckboxPressed;
    public event Action<bool>? OnSkipCheckboxPressed;
    public event Action<int>? OnRecipeCancelled;
    // </Mono>

    public List<ProtoId<LatheRecipePrototype>> Recipes = new();

    public List<ProtoId<LatheCategoryPrototype>>? Categories;

    public ProtoId<LatheCategoryPrototype>? CurrentCategory;

    public EntityUid Entity;

    public LatheMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _spriteSystem = _entityManager.System<SpriteSystem>();
        _lathe = _entityManager.System<LatheSystem>();
        _materialStorage = _entityManager.System<MaterialStorageSystem>();
        _container = _entityManager.System<SharedContainerSystem>(); // mono
        _solution = _entityManager.System<SharedSolutionContainerSystem>(); // mono

        SearchBar.OnTextChanged += _ =>
        {
            PopulateRecipes();
        };
        AmountLineEdit.OnTextChanged += _ =>
        {
            PopulateRecipes();
        };

        FilterOption.OnItemSelected += OnItemSelected;

        ServerListButton.OnPressed += a => OnServerListButtonPressed?.Invoke(a);

        // <Mono>
        LoopCheckbox.OnPressed += _ => OnLoopCheckboxPressed?.Invoke(LoopCheckbox.Pressed);
        SkipCheckbox.OnPressed += _ => OnSkipCheckboxPressed?.Invoke(SkipCheckbox.Pressed);
        // </Mono>
    }

    public void SetEntity(EntityUid uid)
    {
        Entity = uid;

        if (_entityManager.TryGetComponent<LatheComponent>(Entity, out var latheComponent))
        {
            if (!latheComponent.DynamicPacks.Any())
            {
                ServerListButton.Visible = false;
            }
        }

        MaterialsList.SetOwner(Entity);
    }

    protected override void Opened()
    {
        base.Opened();

        if (_entityManager.TryGetComponent<LatheComponent>(Entity, out var latheComp))
        {
            AmountLineEdit.SetText(latheComp.DefaultProductionAmount.ToString());
        }
    }

    /// <summary>
    /// Populates the list of all the recipes
    /// </summary>
    public void PopulateRecipes()
    {
        var recipesToShow = new List<LatheRecipePrototype>();
        foreach (var recipe in Recipes)
        {
            if (!_prototypeManager.TryIndex(recipe, out var proto))
                continue;

            // Category filtering
            if (CurrentCategory != null)
            {
                if (proto.Categories.Count <= 0)
                    continue;

                var validRecipe = proto.Categories.Any(category => category == CurrentCategory);

                if (!validRecipe)
                    continue;
            }

            if (SearchBar.Text.Trim().Length != 0)
            {
                if (_lathe.GetRecipeName(recipe).ToLowerInvariant().Contains(SearchBar.Text.Trim().ToLowerInvariant()))
                    recipesToShow.Add(proto);
            }
            else
            {
                recipesToShow.Add(proto);
            }
        }

        if (!int.TryParse(AmountLineEdit.Text, out var quantity) || quantity <= 0)
            quantity = 1;

        var sortedRecipesToShow = recipesToShow.OrderBy(_lathe.GetRecipeName);
        RecipeList.Children.Clear();
        _entityManager.TryGetComponent(Entity, out LatheComponent? lathe);

        foreach (var prototype in sortedRecipesToShow)
        {
            var canProduce = _lathe.CanProduce(Entity, prototype, quantity, component: lathe);

            var control = new RecipeControl(_lathe, prototype, () => GenerateTooltipText(prototype), canProduce, GetRecipeDisplayControl(prototype));
            control.OnButtonPressed += s =>
            {
                if (!int.TryParse(AmountLineEdit.Text, out var amount) || amount <= 0)
                    amount = 1;
                RecipeQueueAction?.Invoke(s, amount);
            };
            RecipeList.AddChild(control);
        }
    }

    private string GenerateTooltipText(LatheRecipePrototype prototype)
    {
        StringBuilder sb = new();
        var multiplier = _entityManager.GetComponent<LatheComponent>(Entity).FinalMaterialUseMultiplier; // Frontier: MaterialUseMultiplier<FinalMaterialUseMultiplier

        foreach (var (id, amount) in prototype.Materials)
        {
            if (!_prototypeManager.TryIndex(id, out var proto))
                continue;

            var adjustedAmount = SharedLatheSystem.AdjustMaterial(amount, prototype.MaterialDiscountScale, multiplier);
            var sheetVolume = _materialStorage.GetSheetVolume(proto);

            var unit = Loc.GetString(proto.Unit);
            var sheets = adjustedAmount / (float) sheetVolume;

            var availableAmount = _materialStorage.GetMaterialAmount(Entity, id);
            var missingAmount = Math.Max(0, adjustedAmount - availableAmount);
            var missingSheets = missingAmount / (float) sheetVolume;

            var name = Loc.GetString(proto.Name);

            string tooltipText;
            if (missingSheets > 0)
            {
                tooltipText = Loc.GetString("lathe-menu-material-amount-missing", ("amount", sheets), ("missingAmount", missingSheets), ("unit", unit), ("material", name));
            }
            else
            {
                var amountText = Loc.GetString("lathe-menu-material-amount", ("amount", sheets), ("unit", unit));
                tooltipText = Loc.GetString("lathe-menu-tooltip-display", ("material", name), ("amount", amountText));
            }

            sb.AppendLine(tooltipText);
        }

        //mono start
        foreach (var (id, amount) in prototype.Entities)
        {
            if (!_prototypeManager.TryIndex(id, out var proto))
                continue;

            var name = Loc.GetString(proto.Name);
            var currentAmount = GetEntityCount(id);

            var missingAmount = amount - currentAmount;

            string tooltipText;

            if (missingAmount > 0)
                tooltipText = Loc.GetString("lathe-menu-entity-amount-missing", ("amount", amount), ("missingAmount", missingAmount), ("unit", ""), ("material", name));
            else
                tooltipText = Loc.GetString("lathe-menu-tooltip-display", ("material", name), ("amount", amount));

            sb.AppendLine(tooltipText);
        }

        foreach (var (id, amount) in prototype.Reagents)
        {
            if (!_prototypeManager.TryIndex(id, out var proto))
                continue;

            var name = Loc.GetString(proto.LocalizedName);
            var currentAmount = GetReagentAmount(id);

            var missingAmount = amount - currentAmount;

            string tooltipText;

            if (missingAmount > 0)
                tooltipText = Loc.GetString("lathe-menu-reagent-amount-missing", ("amount", amount), ("missingAmount", missingAmount), ("unit", "u"), ("material", name));
            else
                tooltipText = Loc.GetString("lathe-menu-tooltip-display", ("material", name), ("amount", amount));

            sb.AppendLine(tooltipText);
        }
        // mono end

        var desc = _lathe.GetRecipeDescription(prototype);
        if (!string.IsNullOrWhiteSpace(desc))
            sb.AppendLine(Loc.GetString("lathe-menu-description-display", ("description", desc)));

        // Remove last newline
        if (sb.Length > 0)
            sb.Remove(sb.Length - 1, 1);

        return sb.ToString();
    }

    public void UpdateCategories()
    {
        // Get categories from recipes
        var currentCategories = new List<ProtoId<LatheCategoryPrototype>>();
        foreach (var recipeId in Recipes)
        {
            var recipe = _prototypeManager.Index(recipeId);

            if (recipe.Categories.Count <= 0)
                continue;

            foreach (var category in recipe.Categories)
            {
                if (currentCategories.Contains(category))
                    continue;

                currentCategories.Add(category);
            }
        }

        if (Categories != null && (Categories.Count == currentCategories.Count || !Categories.All(currentCategories.Contains)))
            return;

        Categories = currentCategories;
        var sortedCategories = currentCategories
            .Select(p => _prototypeManager.Index(p))
            .OrderBy(p => Loc.GetString(p.Name))
            .ToList();

        FilterOption.Clear();
        FilterOption.AddItem(Loc.GetString("lathe-menu-category-all"), -1);
        foreach (var category in sortedCategories)
        {
            FilterOption.AddItem(Loc.GetString(category.Name), Categories.IndexOf(category.ID));
        }

        FilterOption.SelectId(-1);
    }

    /// <summary>
    /// Populates the build queue list with all queued items
    /// </summary>
    /// <param name="queue"></param>
    public void PopulateQueueList(List<LatheRecipeBatch> queue) // Frontier: LatheRecipePrototype<LatheRecipeBatch
    {
        QueueList.DisposeAllChildren();

        var idx = 1;
        foreach (var batch in queue) // Frontier: recipe<batch
        {
            var queuedRecipeBox = new BoxContainer();
            queuedRecipeBox.Orientation = BoxContainer.LayoutOrientation.Horizontal;

            // Frontier: batch handling
            queuedRecipeBox.AddChild(GetRecipeDisplayControl(batch.Recipe));

            var queuedRecipeLabel = new Label();
            if (batch.ItemsRequested > 1)
                queuedRecipeLabel.Text = $"{idx}. {_lathe.GetRecipeName(batch.Recipe)} ({batch.ItemsPrinted}/{batch.ItemsRequested})";
            else
                queuedRecipeLabel.Text = $"{idx}. {_lathe.GetRecipeName(batch.Recipe)}";
            // End Frontier
            queuedRecipeBox.AddChild(queuedRecipeLabel);
            // <Mono>
            var cancelButton = new Button();
            cancelButton.Text = "X";
            cancelButton.StyleClasses.Add(StyleBase.ButtonCaution);
            cancelButton.OnPressed += _ => OnRecipeCancelled?.Invoke(batch.Index);
            queuedRecipeBox.AddChild(cancelButton);
            // </Mono>
            QueueList.AddChild(queuedRecipeBox);
            idx++;
        }
    }

    public void SetQueueInfo(LatheRecipePrototype? recipe)
    {
        FabricatingContainer.Visible = recipe != null;
        if (recipe == null)
            return;

        FabricatingDisplayContainer.Children.Clear();
        FabricatingDisplayContainer.AddChild(GetRecipeDisplayControl(recipe));

        NameLabel.Text = _lathe.GetRecipeName(recipe);
    }

    // <Mono>
    public void SetLooping(bool loop)
    {
        LoopCheckbox.Pressed = loop;
    }

    public void SetSkipping(bool skip)
    {
        SkipCheckbox.Pressed = skip;
    }
    // </Mono>

    public Control GetRecipeDisplayControl(LatheRecipePrototype recipe)
    {
        if (recipe.Icon != null)
        {
            var textRect = new TextureRect();
            textRect.Texture = _spriteSystem.Frame0(recipe.Icon);
            return textRect;
        }

        if (recipe.Result is { } result)
        {
            var entProtoView = new EntityPrototypeView();
            entProtoView.SetPrototype(result);
            return entProtoView;
        }

        return new Control();
    }

    private void OnItemSelected(OptionButton.ItemSelectedEventArgs obj)
    {
        FilterOption.SelectId(obj.Id);
        if (obj.Id == -1)
        {
            CurrentCategory = null;
        }
        else
        {
            CurrentCategory = Categories?[obj.Id];
        }
        PopulateRecipes();
    }

    // mono
    private int GetEntityCount(EntProtoId recipeEnt)
    {
        var count = 0;

        if (!_entityManager.TryGetComponent<EntityStorageComponent>(Entity, out var storage))
            return count;

        foreach (var containedEnt in storage.Contents.ContainedEntities)
        {
            if ( _entityManager.GetComponent<MetaDataComponent>(containedEnt).EntityPrototype is not { } proto
                || proto.ID != recipeEnt)
                continue;

            if (_entityManager.TryGetComponent<StackComponent>(containedEnt, out var stack))
                count += stack.Count;
            else
                count += 1;
        }

        return count;
    }

    // mono
    private FixedPoint2 GetReagentAmount(ProtoId<ReagentPrototype> recipeReag)
    {
        if (!_entityManager.TryGetComponent<LatheComponent>(Entity, out var lathe) ||
            lathe.ReagentOutputSlotId is not { } slotId)
            return 0;

        if (!_container.TryGetContainer(Entity, slotId, out var container) ||
            container.ContainedEntities.Count == 0)
            return 0;

        if (!_solution.TryGetDrainableSolution(container.ContainedEntities[0], out _, out var solution))
            return 0;

        return solution.GetReagentQuantity(new ReagentId(recipeReag, []));
    }
}
