// LuaCorp - This file is licensed under AGPLv3
// Copyright (c) 2026 LuaCorp Contributors
// See AGPLv3.txt for details.

using System;
using System.Collections.Generic;
using System.Numerics;
using Content.Client.Interaction;
using Content.Client.Stylesheets;
using Content.Client.UserInterface.Controls;
using Content.Shared._Lua.AmmoLoader;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.Input;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.GameObjects;
using Robust.Shared.Input;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;
using Robust.Shared.Utility;
using Key = Robust.Client.Input.Keyboard.Key;

namespace Content.Client._Lua.AmmoLoader.UI;

[GenerateTypedNameReferences]
public sealed partial class AmmoLoaderWindow : FancyWindow
{
    private enum InfoMode : byte
    {
        None,
        StorageAmmo,
        Turret,
        TurretLoadedAmmo,
    }

    private static readonly Color PanelBg = Color.FromHex("#111820");
    private static readonly Color SlotBg = Color.FromHex("#11171e");
    private static readonly Color SlotBorder = Color.FromHex("#2c3846");
    private static readonly Color SlotSelectedBorder = Color.FromHex("#7ec8e3");
    private static readonly Color Accent = Color.FromHex("#7ec8e3");
    private static readonly Color DropHighlight = Color.FromHex("#1c3540");
    private static readonly Vector2 SlotSize = new(108, 126);
    private static readonly Vector2 QuickSlotSize = new(48, 48);
    private static readonly Vector2 TurretSlotSize = new(48, 48);
    private const int QuickUnloadSlotCount = 8;
    private const int StorageColumns = 5;
    private const int DefaultTurretColumns = 16;
    [Dependency] private readonly IPrototypeManager _prototypes = default!;
    [Dependency] private readonly IInputManager _input = default!;
    private readonly List<AmmoLoaderInventoryGroup> _groups = new();
    private readonly List<AmmoLoaderLinkedTurret> _linkedTurrets = new();
    private readonly Dictionary<string, PanelContainer> _slotPanels = new();
    private readonly Dictionary<string, MarqueeLabel> _slotTitles = new();
    private readonly Dictionary<NetEntity, PanelContainer> _turretPanels = new();
    private readonly List<PanelContainer> _quickSlots = new();
    private readonly List<EntityPrototypeView> _quickIcons = new();
    private readonly string?[] _quickQueue = new string?[QuickUnloadSlotCount];
    private readonly DragDropHelper<string> _dragHelper;
    private readonly EntityPrototypeView _dragShadow;
    private readonly PanelContainer _turretLoadedBg;
    private readonly EntityPrototypeView _turretLoadedIcon;
    private EntProtoId? _selectedAmmo;
    private bool _selectedEmpty;
    private NetEntity? _selectedTurret;
    private InfoMode _infoMode = InfoMode.None;
    private int _maxConnections = DefaultTurretColumns;
    private bool _dragMouseHeld;
    private bool _dragFromQuick;
    private bool _dragFromTurretSlot;
    private bool _dragFromEmpty;
    private int _dragQuickSlot = -1;
    public event Action<EntProtoId, bool>? OnUnloadOne;
    public event Action<NetEntity, EntProtoId>? OnLoadTurret;
    public event Action<NetEntity>? OnUnloadTurret;

    public AmmoLoaderWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        AmmoGrid.Columns = StorageColumns;
        TurretGrid.Columns = DefaultTurretColumns;
        _dragHelper = new DragDropHelper<string>(OnBeginDrag, OnContinueDrag, OnEndDrag);
        _dragShadow = new EntityPrototypeView
        {
            SetSize = new Vector2(48, 48),
            Visible = false,
            MouseFilter = MouseFilterMode.Ignore,
        };
        ConfigurePrototypeIcon(_dragShadow);
        EjectAllButton.OnPressed += _ => EjectQuickUnloadQueue();
        UnloadOneButton.OnPressed += _ => OnUnloadPressed();
        ConfigurePrototypeIcon(SelectedIcon);
        LayoutContainer.SetAnchorAndMarginPreset(SelectedIcon, LayoutContainer.LayoutPreset.Wide, margin: 34);
        LayoutContainer.SetAnchorAndMarginPreset(SelectedNameMarquee, LayoutContainer.LayoutPreset.TopWide, margin: 0);
        LayoutContainer.SetAnchorAndMarginPreset(SelectedCountLabel, LayoutContainer.LayoutPreset.BottomWide, margin: 8);
        SelectedNameMarquee.FontColorOverride = Accent;
        _turretLoadedBg = new PanelContainer
        {
            HorizontalExpand = true,
            VerticalExpand = true,
            MouseFilter = MouseFilterMode.Ignore,
            PanelOverride = MakeSlotStyle(false),
        };
        TurretLoadedSlot.AddChild(_turretLoadedBg);
        LayoutContainer.SetAnchorPreset(_turretLoadedBg, LayoutContainer.LayoutPreset.Wide);
        _turretLoadedIcon = new EntityPrototypeView
        {
            MouseFilter = MouseFilterMode.Ignore,
            Visible = false,
        };
        ConfigurePrototypeIcon(_turretLoadedIcon);
        TurretLoadedSlot.AddChild(_turretLoadedIcon);
        LayoutContainer.SetAnchorAndMarginPreset(_turretLoadedIcon, LayoutContainer.LayoutPreset.Wide, margin: 6);
        TurretLoadedSlot.OnKeyBindDown += args =>
        {
            if (args.Function != EngineKeyFunctions.UIClick) return;
            if (_selectedTurret is not { } turret) return;
            var loaded = GetSelectedTurretState()?.LoadedAmmoPrototype;
            if (loaded == null) return;
            SelectTurretLoadedAmmo(loaded.Value);
            _dragFromQuick = false;
            _dragFromTurretSlot = true;
            _dragQuickSlot = -1;
            _dragMouseHeld = true;
            _dragHelper.MouseDown(loaded.Value.Id);
            args.Handle();
        };
        TurretLoadedSlot.OnKeyBindUp += args =>
        { if (args.Function == EngineKeyFunctions.UIClick) args.Handle(); };
        BuildQuickUnloadSlots();
        RefreshQuickUnloadVisuals();
        AddTurretPlaceholders();
    }
    protected override void EnteredTree()
    {
        base.EnteredTree();
        if (_dragShadow.Parent == null) UserInterfaceManager.PopupRoot.AddChild(_dragShadow);
    }
    protected override void ExitedTree()
    {
        base.ExitedTree();
        _dragMouseHeld = false;
        _dragFromQuick = false;
        _dragFromTurretSlot = false;
        _dragFromEmpty = false;
        _dragQuickSlot = -1;
        _dragHelper.EndDrag();
        _dragShadow.Orphan();
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);
        _dragHelper.Update(args.DeltaSeconds);
        if (!_dragMouseHeld) return;
        if (_input.IsKeyDown(Key.MouseLeft)) return;
        var wasDragging = _dragHelper.IsDragging;
        var dragged = _dragHelper.Dragged;
        var mouse = UserInterfaceManager.MousePositionScaled.Position;
        var overQuick = QuickUnloadPanel.GlobalRect.Contains(mouse);
        var overStorage = StoragePanel.GlobalRect.Contains(mouse);
        var turretMode = _selectedTurret != null && _infoMode is (InfoMode.Turret or InfoMode.TurretLoadedAmmo);
        var overTurretDrop = turretMode && TurretLoadedSection.Visible && (TurretLoadedSlot.GlobalRect.Contains(mouse) || TurretLoadedSection.GlobalRect.Contains(mouse) || InfoPanel.GlobalRect.Contains(mouse));
        _dragMouseHeld = false;
        if (wasDragging && dragged != null)
        {
            if (_dragFromQuick)
            { HandleQuickDragEnd(overQuick); }
            else if (_dragFromTurretSlot)
            { if (overStorage) TryUnloadSelectedTurret(); }
            else if (overTurretDrop)
            { if (!_dragFromEmpty) TryLoadSelectedTurret(dragged); }
            else if (overQuick)
            { TryStageQuickUnload(dragged); }
        }
        else if (!wasDragging && !_dragFromQuick && !_dragFromTurretSlot && dragged != null && _selectedTurret != null && _infoMode is (InfoMode.Turret or InfoMode.TurretLoadedAmmo))
        { SelectStorageAmmo(new EntProtoId(dragged), _dragFromEmpty); }
        _dragFromQuick = false;
        _dragFromTurretSlot = false;
        _dragFromEmpty = false;
        _dragQuickSlot = -1;
        _dragHelper.EndDrag();
    }

    public void UpdateState(AmmoLoaderBoundUserInterfaceState state)
    {
        _groups.Clear();
        _groups.AddRange(state.Groups);
        _linkedTurrets.Clear();
        if (state.LinkedTurrets != null) _linkedTurrets.AddRange(state.LinkedTurrets);
        _maxConnections = Math.Max(1, state.MaxConnections > 0 ? state.MaxConnections : DefaultTurretColumns);
        TurretGrid.Columns = _maxConnections;
        _slotPanels.Clear();
        _slotTitles.Clear();
        _turretPanels.Clear();
        AmmoGrid.DisposeAllChildren();
        TurretGrid.DisposeAllChildren();
        if (_selectedAmmo is { } selectedAmmo && !_groups.Exists(g => g.PrototypeId.Id == selectedAmmo.Id && g.IsEmpty == _selectedEmpty))
        {
            _selectedAmmo = null;
            _selectedEmpty = false;
        }
        if (_selectedTurret is { } selectedTurret && !_linkedTurrets.Exists(t => t.Turret == selectedTurret))
        {
            _selectedTurret = null;
            if (_infoMode is InfoMode.Turret or InfoMode.TurretLoadedAmmo) _infoMode = InfoMode.None;
        }
        if (_selectedAmmo == null && _selectedTurret == null && _infoMode == InfoMode.None && _groups.Count > 0)
        { SelectStorageAmmo(_groups[0].PrototypeId, _groups[0].IsEmpty); }
        foreach (var group in _groups) AmmoGrid.AddChild(CreateGroupSlot(group));
        AddStoragePlaceholders();
        foreach (var turret in _linkedTurrets) TurretGrid.AddChild(CreateTurretSlot(turret));
        AddTurretPlaceholders();
        TurretGrid.MinHeight = 56;
        TotalLabel.Text = Loc.GetString("ammo-loader-window-total", ("current", state.CurrentCount), ("max", state.MaxCapacity));
        LinkedTurretsPanel.Visible = true;
        PruneQuickUnloadAgainstStorage();
        RefreshQuickUnloadVisuals();
        RefreshSelectionPanel();
        UpdateEjectButtonState();
        RefreshTurretSelectionBorders();
    }

    private void OnUnloadPressed()
    {
        if (_infoMode is InfoMode.Turret or InfoMode.TurretLoadedAmmo)
        {
            TryUnloadSelectedTurret();
            return;
        }
        if (_selectedAmmo is { } selected) OnUnloadOne?.Invoke(selected, _selectedEmpty);
    }

    private void TryLoadSelectedTurret(string prototypeId)
    {
        if (_selectedTurret is not { } turret) return;
        var turretState = GetSelectedTurretState();
        if (turretState is not { CanModifyAmmo: true }) return;
        if (GetAvailableCount(prototypeId) <= 0) return;
        OnLoadTurret?.Invoke(turret, new EntProtoId(prototypeId));
    }

    private void TryUnloadSelectedTurret()
    {
        if (_selectedTurret is not { } turret) return;
        var turretState = GetSelectedTurretState();
        if (turretState is not { CanModifyAmmo: true } || turretState.AmmoCount <= 0) return;
        OnUnloadTurret?.Invoke(turret);
    }

    private AmmoLoaderLinkedTurret? GetSelectedTurretState()
    {
        if (_selectedTurret is not { } selected) return null;
        foreach (var turret in _linkedTurrets)
        { if (turret.Turret == selected) return turret; }
        return null;
    }

    private void BuildQuickUnloadSlots()
    {
        QuickUnloadSlots.DisposeAllChildren();
        _quickSlots.Clear();
        _quickIcons.Clear();
        for (var i = 0; i < QuickUnloadSlotCount; i++)
        {
            var slotIndex = i;
            var slot = new LayoutContainer
            {
                MinSize = QuickSlotSize,
                MaxSize = QuickSlotSize,
                SetSize = QuickSlotSize,
                HorizontalExpand = false,
                VerticalExpand = false,
                MouseFilter = MouseFilterMode.Stop,
            };
            var bg = new PanelContainer
            {
                HorizontalExpand = true,
                VerticalExpand = true,
                MouseFilter = MouseFilterMode.Ignore,
                PanelOverride = MakeSlotStyle(false),
            };
            slot.AddChild(bg);
            LayoutContainer.SetAnchorPreset(bg, LayoutContainer.LayoutPreset.Wide);
            var icon = new EntityPrototypeView
            {
                MouseFilter = MouseFilterMode.Ignore,
                Visible = false,
            };
            ConfigurePrototypeIcon(icon);
            slot.AddChild(icon);
            LayoutContainer.SetAnchorAndMarginPreset(icon, LayoutContainer.LayoutPreset.Wide, margin: 6);
            slot.OnKeyBindDown += args =>
            {
                if (args.Function != EngineKeyFunctions.UIClick) return;
                if (_quickQueue[slotIndex] is not { } protoId) return;
                _dragFromQuick = true;
                _dragFromTurretSlot = false;
                _dragQuickSlot = slotIndex;
                _dragMouseHeld = true;
                _dragHelper.MouseDown(protoId);
                args.Handle();
            };
            slot.OnKeyBindUp += args =>
            { if (args.Function == EngineKeyFunctions.UIClick) args.Handle(); };
            QuickUnloadSlots.AddChild(slot);
            _quickSlots.Add(bg);
            _quickIcons.Add(icon);
        }
    }

    private Control CreateGroupSlot(AmmoLoaderInventoryGroup group)
    {
        var name = group.PrototypeId.Id;
        if (_prototypes.TryIndex(group.PrototypeId, out var proto)) name = proto.Name;
        var slotName = GetStorageSlotName(group.PrototypeId, name);
        var selected = _selectedAmmo?.Id == group.PrototypeId.Id && _selectedEmpty == group.IsEmpty && _infoMode == InfoMode.StorageAmmo;
        var panel = new PanelContainer
        {
            MinSize = SlotSize,
            MaxSize = SlotSize,
            SetSize = SlotSize,
            HorizontalExpand = false,
            VerticalExpand = false,
            PanelOverride = new StyleBoxFlat
            {
                BackgroundColor = SlotBg,
                BorderColor = selected ? SlotSelectedBorder : SlotBorder,
                BorderThickness = new Thickness(2),
            },
        };
        var content = new LayoutContainer
        {
            Margin = new Thickness(3),
            HorizontalExpand = false,
            MinSize = new Vector2(102, 120),
            MaxSize = new Vector2(102, 120),
            SetSize = new Vector2(102, 120),
        };
        var iconArea = new LayoutContainer
        {
            MinSize = new Vector2(102, 92),
            MaxSize = new Vector2(102, 92),
            SetSize = new Vector2(102, 92),
            HorizontalExpand = false,
            MouseFilter = MouseFilterMode.Stop,
            RectClipContent = true,
        };
        var icon = new EntityPrototypeView
        { MouseFilter = MouseFilterMode.Ignore, };
        ConfigurePrototypeIcon(icon);
        icon.SetPrototype(group.PrototypeId);
        iconArea.AddChild(icon);
        LayoutContainer.SetAnchorAndMarginPreset(icon, LayoutContainer.LayoutPreset.Wide, margin: 16);
        content.AddChild(iconArea);
        LayoutContainer.SetAnchorAndMarginPreset(iconArea, LayoutContainer.LayoutPreset.TopWide, margin: 0);
        var titleBar = new PanelContainer
        {
            MouseFilter = MouseFilterMode.Ignore,
            MinHeight = 18,
            MaxHeight = 18,
            PanelOverride = new StyleBoxFlat
            {
                BackgroundColor = Color.FromHex("#151d26e6"),
                BorderColor = Color.Transparent,
            },
        };
        var title = new MarqueeLabel
        {
            Text = slotName,
            FontColorOverride = selected ? Accent : Color.FromHex("#d0d6e0"),
            MinHeight = 18,
            MaxHeight = 18,
            HorizontalExpand = true,
        };
        titleBar.AddChild(title);
        content.AddChild(titleBar);
        LayoutContainer.SetAnchorAndMarginPreset(titleBar, LayoutContainer.LayoutPreset.TopWide, margin: 0);
        var countLabel = new Label
        {
            Text = FormatGroupCount(group),
            FontColorOverride = group.IsEmpty ? Color.FromHex("#8a93a3") : Color.FromHex("#e8eef6"),
            MouseFilter = MouseFilterMode.Ignore,
            Margin = new Thickness(0, 0, 3, 2),
        };
        iconArea.AddChild(countLabel);
        LayoutContainer.SetAnchorAndMarginPreset(countLabel, LayoutContainer.LayoutPreset.BottomRight, margin: 1);
        var groupKey = GetGroupKey(group);
        _slotPanels[groupKey] = panel;
        _slotTitles[groupKey] = title;
        var protoId = group.PrototypeId;
        var isEmpty = group.IsEmpty;
        iconArea.OnKeyBindDown += args =>
        {
            if (args.Function != EngineKeyFunctions.UIClick) return;
            if (_selectedTurret == null || _infoMode is not (InfoMode.Turret or InfoMode.TurretLoadedAmmo)) SelectStorageAmmo(protoId, isEmpty);
            _dragFromQuick = false;
            _dragFromTurretSlot = false;
            _dragFromEmpty = isEmpty;
            _dragQuickSlot = -1;
            _dragMouseHeld = true;
            _dragHelper.MouseDown(protoId.Id);
            args.Handle();
        };
        iconArea.OnKeyBindUp += args =>
        {
            if (args.Function == EngineKeyFunctions.UIClick) args.Handle();
        };
        var unloadButton = new Button
        {
            Text = Loc.GetString("ammo-loader-window-unload"),
            HorizontalExpand = true,
            MinSize = new Vector2(102, 24),
            MaxSize = new Vector2(102, 24),
            SetSize = new Vector2(102, 24),
            StyleClasses = { StyleBase.ButtonOpenBoth },
        };
        unloadButton.OnPressed += _ =>
        {
            SelectStorageAmmo(protoId, isEmpty);
            OnUnloadOne?.Invoke(protoId, isEmpty);
        };
        content.AddChild(unloadButton);
        LayoutContainer.SetAnchorAndMarginPreset(unloadButton, LayoutContainer.LayoutPreset.BottomWide, margin: 0);
        panel.AddChild(content);
        return panel;
    }
    private Control CreateTurretSlot(AmmoLoaderLinkedTurret turret)
    {
        var selected = _selectedTurret == turret.Turret && _infoMode is InfoMode.Turret or InfoMode.TurretLoadedAmmo;
        var slot = new LayoutContainer
        {
            MinSize = TurretSlotSize,
            MaxSize = TurretSlotSize,
            SetSize = TurretSlotSize,
            HorizontalExpand = false,
            VerticalExpand = false,
            MouseFilter = MouseFilterMode.Stop,
            ToolTip = $"{turret.TurretName} ({turret.AmmoCount}/{turret.AmmoCapacity})",
        };
        var bg = new PanelContainer
        {
            HorizontalExpand = true,
            VerticalExpand = true,
            MouseFilter = MouseFilterMode.Ignore,
            PanelOverride = new StyleBoxFlat
            {
                BackgroundColor = selected ? Color.FromHex("#1a2c35") : Color.FromHex("#0d1319"),
                BorderColor = selected ? SlotSelectedBorder : SlotBorder,
                BorderThickness = new Thickness(2),
            },
        };
        slot.AddChild(bg);
        LayoutContainer.SetAnchorPreset(bg, LayoutContainer.LayoutPreset.Wide);
        var icon = new EntityPrototypeView
        { MouseFilter = MouseFilterMode.Ignore, };
        ConfigureTurretIcon(icon);
        icon.SetPrototype(turret.TurretPrototype);
        slot.AddChild(icon);
        LayoutContainer.SetAnchorAndMarginPreset(icon, LayoutContainer.LayoutPreset.Wide, margin: 2);
        _turretPanels[turret.Turret] = bg;
        var turretNet = turret.Turret;
        slot.OnKeyBindDown += args =>
        {
            if (args.Function != EngineKeyFunctions.UIClick) return;
            SelectTurret(turretNet);
            args.Handle();
        };
        slot.OnKeyBindUp += args =>
        { if (args.Function == EngineKeyFunctions.UIClick) args.Handle(); };
        return slot;
    }

    private static string GetStorageSlotName(EntProtoId prototypeId, string fallbackName)
    {
        var label = AmmoLoaderLocale.GetAmmoCaliber(prototypeId.Id, fallbackName);
        return CompactAmmoLabel(label);
    }

    private static string CompactAmmoLabel(string label)//shit code, mb any idea?
    {
        label = RemovePrefix(label, "магазин ");
        label = RemovePrefix(label, "ящик ");
        label = RemovePrefix(label, "блок ");
        label = RemovePrefix(label, "magazine ");
        label = RemovePrefix(label, "box ");
        label = RemoveToken(label, " ammo loader");
        label = RemoveToken(label, " ammo box");
        label = RemoveToken(label, " magazine");
        label = RemoveToken(label, " box");
        return label.Trim();
    }

    private static string RemovePrefix(string value, string prefix)
    { return value.StartsWith(prefix, StringComparison.OrdinalIgnoreCase) ? value[prefix.Length..] : value; }
    private static string RemoveToken(string value, string token)
    {
        var index = value.IndexOf(token, StringComparison.OrdinalIgnoreCase);
        return index >= 0 ? value.Remove(index, token.Length) : value;
    }

    private void SelectStorageAmmo(EntProtoId prototypeId, bool empty = false)
    {
        _selectedAmmo = prototypeId;
        _selectedEmpty = empty;
        _infoMode = InfoMode.StorageAmmo;
        RefreshTurretSelectionBorders();
        var selectedKey = GetGroupKey(prototypeId, empty);
        foreach (var (id, panel) in _slotPanels)
        {
            var isSelected = id == selectedKey;
            panel.PanelOverride = new StyleBoxFlat
            {
                BackgroundColor = SlotBg,
                BorderColor = isSelected ? SlotSelectedBorder : SlotBorder,
                BorderThickness = new Thickness(2),
            };
            if (_slotTitles.TryGetValue(id, out var title)) title.FontColorOverride = isSelected ? Accent : Color.FromHex("#d0d6e0");
        }
        RefreshSelectionPanel();
    }

    private void SelectTurret(NetEntity turret)
    {
        _selectedTurret = turret;
        _infoMode = InfoMode.Turret;
        foreach (var (id, panel) in _slotPanels)
        {
            panel.PanelOverride = new StyleBoxFlat
            {
                BackgroundColor = SlotBg,
                BorderColor = SlotBorder,
                BorderThickness = new Thickness(2),
            };
            if (_slotTitles.TryGetValue(id, out var title)) title.FontColorOverride = Color.FromHex("#d0d6e0");
        }
        RefreshTurretSelectionBorders();
        RefreshSelectionPanel();
    }

    private void RefreshTurretSelectionBorders()
    {
        foreach (var (netEntity, panel) in _turretPanels)
        {
            var isSelected = netEntity == _selectedTurret && _infoMode is InfoMode.Turret or InfoMode.TurretLoadedAmmo;
            panel.PanelOverride = new StyleBoxFlat
            {
                BackgroundColor = isSelected ? Color.FromHex("#1a2c35") : Color.FromHex("#0d1319"),
                BorderColor = isSelected ? SlotSelectedBorder : SlotBorder,
                BorderThickness = new Thickness(2),
            };
        }
    }

    private void SelectTurretLoadedAmmo(EntProtoId prototypeId)
    {
        _selectedAmmo = prototypeId;
        _infoMode = InfoMode.TurretLoadedAmmo;
        RefreshSelectionPanel();
    }

    private void RefreshSelectionPanel()
    {
        if (_infoMode is InfoMode.Turret or InfoMode.TurretLoadedAmmo)
        {
            RefreshTurretSelectionPanel();
            return;
        }
        TurretLoadedSection.Visible = false;
        InfoHeadingLabel.Text = Loc.GetString("ammo-loader-window-item-info");
        if (_selectedAmmo is not { } selected || !_groups.Exists(g => g.PrototypeId.Id == selected.Id && g.IsEmpty == _selectedEmpty))
        {
            SelectedNameMarquee.Text = Loc.GetString("ammo-loader-window-no-selection");
            SelectedDescLabel.SetMessage(string.Empty);
            SelectedCountLabel.Text = string.Empty;
            SelectedIcon.SetPrototype(null);
            UnloadOneButton.Disabled = true;
            return;
        }
        var group = _groups.Find(g => g.PrototypeId.Id == selected.Id && g.IsEmpty == _selectedEmpty);
        if (group == null)
        {
            SelectedNameMarquee.Text = Loc.GetString("ammo-loader-window-no-selection");
            SelectedDescLabel.SetMessage(string.Empty);
            SelectedCountLabel.Text = string.Empty;
            SelectedIcon.SetPrototype(null);
            UnloadOneButton.Disabled = true;
            return;
        }
        var name = selected.Id;
        if (_prototypes.TryIndex(selected, out var proto)) name = proto.Name;
        SelectedNameMarquee.Text = name;
        SelectedNameMarquee.ResetScroll();
        SelectedDescLabel.SetMessage(FormattedMessage.FromMarkupPermissive( AmmoLoaderLocale.FormatItemStats(selected.Id, name)));
        SelectedCountLabel.Text = FormatGroupCount(group);
        SelectedIcon.SetPrototype(selected);
        UnloadOneButton.Text = Loc.GetString("ammo-loader-window-unload-one");
        UnloadOneButton.Disabled = false;
    }

    private void RefreshTurretSelectionPanel()
    {
        var turret = GetSelectedTurretState();
        if (turret == null)
        {
            SelectedNameMarquee.Text = Loc.GetString("ammo-loader-window-no-selection");
            SelectedDescLabel.SetMessage(string.Empty);
            SelectedCountLabel.Text = string.Empty;
            SelectedIcon.SetPrototype(null);
            TurretLoadedSection.Visible = false;
            UnloadOneButton.Disabled = true;
            return;
        }
        InfoHeadingLabel.Text = Loc.GetString("ammo-loader-window-turret-info");
        TurretLoadedSection.Visible = true;
        SelectedNameMarquee.Text = turret.TurretName;
        SelectedNameMarquee.ResetScroll();
        SelectedCountLabel.Text = Loc.GetString("ammo-loader-window-turret-ammo", ("current", turret.AmmoCount), ("max", turret.AmmoCapacity));
        SelectedIcon.SetPrototype(turret.TurretPrototype);
        if (_infoMode == InfoMode.TurretLoadedAmmo && (_selectedAmmo ?? turret.LoadedAmmoPrototype) is { } loadedAmmo)
        {
            var ammoName = loadedAmmo.Id;
            if (_prototypes.TryIndex(loadedAmmo, out var ammoProto)) ammoName = ammoProto.Name;
            SelectedDescLabel.SetMessage(FormattedMessage.FromMarkupPermissive(AmmoLoaderLocale.FormatItemStats(loadedAmmo.Id, ammoName)));
            _turretLoadedBg.PanelOverride = MakeSlotStyle(true);
        }
        else
        {
            SelectedDescLabel.SetMessage(string.Empty);
            _turretLoadedBg.PanelOverride = MakeSlotStyle(false);
        }
        if (turret.LoadedAmmoPrototype is { } loadedProto)
        {
            _turretLoadedIcon.Visible = true;
            _turretLoadedIcon.SetPrototype(loadedProto);
            TurretLoadedSlot.MouseFilter = MouseFilterMode.Stop;
        }
        else
        {
            _turretLoadedIcon.Visible = false;
            _turretLoadedIcon.SetPrototype(null);
            TurretLoadedSlot.MouseFilter = MouseFilterMode.Stop;
        }
        var canUnload = turret.CanModifyAmmo && turret.AmmoCount > 0;
        UnloadOneButton.Text = Loc.GetString("ammo-loader-window-unload-turret");
        UnloadOneButton.Disabled = !canUnload;
    }

    private void HandleQuickDragEnd(bool overQuick)
    {
        if (_dragQuickSlot < 0 || _dragQuickSlot >= _quickQueue.Length) return;
        if (!overQuick) _quickQueue[_dragQuickSlot] = null;
        RefreshQuickUnloadVisuals();
        UpdateEjectButtonState();
    }

    private bool TryStageQuickUnload(string prototypeId)
    {
        if (IsTypeStaged(prototypeId)) return false;
        if (GetAvailableCount(prototypeId) <= 0) return false;
        for (var i = 0; i < _quickQueue.Length; i++)
        {
            if (_quickQueue[i] != null) continue;
            _quickQueue[i] = prototypeId;
            RefreshQuickUnloadVisuals();
            UpdateEjectButtonState();
            return true;
        }
        return false;
    }

    private void EjectQuickUnloadQueue()
    {
        var stagedTypes = new List<string>();
        foreach (var id in _quickQueue)
        {
            if (id == null || stagedTypes.Contains(id)) continue;
            stagedTypes.Add(id);
        }
        foreach (var type in stagedTypes)
        {
            var count = GetAvailableCount(type);
            for (var i = 0; i < count; i++) OnUnloadOne?.Invoke(new EntProtoId(type), false);
        }
        Array.Clear(_quickQueue);
        RefreshQuickUnloadVisuals();
        UpdateEjectButtonState();
    }

    private void PruneQuickUnloadAgainstStorage()
    {
        for (var i = 0; i < _quickQueue.Length; i++)
        {
            var id = _quickQueue[i];
            if (id == null) continue;
            if (GetAvailableCount(id) <= 0) _quickQueue[i] = null;
        }
    }

    private void RefreshQuickUnloadVisuals()
    {
        for (var i = 0; i < _quickIcons.Count; i++)
        {
            var id = _quickQueue[i];
            var icon = _quickIcons[i];
            if (id == null)
            {
                icon.Visible = false;
                icon.SetPrototype(null);
            }
            else
            {
                icon.Visible = true;
                icon.SetPrototype(id);
            }
            _quickSlots[i].PanelOverride = MakeSlotStyle(false);
        }
    }

    private void AddStoragePlaceholders()
    {
        var targetSlots = Math.Max(StorageColumns * 2, ((_groups.Count + StorageColumns - 1) / StorageColumns) * StorageColumns);
        for (var i = _groups.Count; i < targetSlots; i++)
        {
            AmmoGrid.AddChild(new PanelContainer
            {
                MinSize = SlotSize,
                MaxSize = SlotSize,
                SetSize = SlotSize,
                HorizontalExpand = false,
                VerticalExpand = false,
                PanelOverride = new StyleBoxFlat
                {
                    BackgroundColor = Color.FromHex("#0d1319"),
                    BorderColor = Color.FromHex("#24313d"),
                    BorderThickness = new Thickness(2),
                },
            });
        }
    }

    private void AddTurretPlaceholders()
    {
        var columns = Math.Max(1, _maxConnections);
        var targetSlots = Math.Max(columns, ((_linkedTurrets.Count + columns - 1) / columns) * columns);
        for (var i = _linkedTurrets.Count; i < targetSlots; i++)
        {
            TurretGrid.AddChild(new PanelContainer
            {
                MinSize = TurretSlotSize,
                MaxSize = TurretSlotSize,
                SetSize = TurretSlotSize,
                HorizontalExpand = false,
                VerticalExpand = false,
                PanelOverride = new StyleBoxFlat
                {
                    BackgroundColor = Color.FromHex("#0d1319"),
                    BorderColor = Color.FromHex("#24313d"),
                    BorderThickness = new Thickness(2),
                },
            });
        }
    }

    private void UpdateEjectButtonState()
    {
        var hasStaged = false;
        foreach (var id in _quickQueue)
        {
            if (id == null) continue;
            hasStaged = true;
            break;
        }
        EjectAllButton.Disabled = !hasStaged;
    }

    private bool IsTypeStaged(string prototypeId)
    {
        foreach (var id in _quickQueue)
        { if (id == prototypeId) return true; }
        return false;
    }

    private int GetAvailableCount(string prototypeId)
    {
        foreach (var group in _groups)
        {
            if (group.IsEmpty) continue;
            if (group.PrototypeId.Id == prototypeId) return group.Count;
        }
        return 0;
    }

    private static string FormatGroupCount(AmmoLoaderInventoryGroup group)
    {
        if (group.IsEmpty)
        { return group.Count > 1 ? Loc.GetString("ammo-loader-window-empty-count", ("count", group.Count)) : Loc.GetString("ammo-loader-window-empty"); }
        return Loc.GetString("ammo-loader-window-count", ("count", group.Count));
    }

    private static string GetGroupKey(AmmoLoaderInventoryGroup group)
    { return GetGroupKey(group.PrototypeId, group.IsEmpty); }
    private static string GetGroupKey(EntProtoId prototypeId, bool empty)
    { return empty ? $"{prototypeId.Id}#empty" : prototypeId.Id; }
    private static void ConfigurePrototypeIcon(EntityPrototypeView view)
    {
        view.Scale = Vector2.One;
        view.Stretch = SpriteView.StretchMode.Fill;
        view.SpriteOffset = false;
    }

    private static void ConfigureTurretIcon(EntityPrototypeView view)
    {
        view.Scale = Vector2.One;
        view.Stretch = SpriteView.StretchMode.Fit;
        view.SpriteOffset = false;
        view.OverrideDirection = Direction.South;
    }

    private static StyleBoxFlat MakeSlotStyle(bool active)
    {
        return new StyleBoxFlat
        {
            BackgroundColor = active ? Color.FromHex("#1a2c35") : Color.FromHex("#0d1319"),
            BorderColor = active ? Accent : SlotBorder,
            BorderThickness = new Thickness(2),
        };
    }

    private bool OnBeginDrag()
    {
        if (_dragHelper.Dragged is not { } dragged) return false;
        _dragShadow.SetPrototype(dragged);
        _dragShadow.Visible = true;
        SetQuickUnloadHighlight(true);
        SetStorageHighlight(false);
        SetTurretLoadedHighlight(false);
        return true;
    }

    private bool OnContinueDrag(float _)
    {
        var mouse = UserInterfaceManager.MousePositionScaled;
        LayoutContainer.SetPosition(_dragShadow, mouse.Position - _dragShadow.Size / 2f);
        if (_dragFromTurretSlot)
        {
            SetStorageHighlight(StoragePanel.GlobalRect.Contains(mouse.Position));
            SetQuickUnloadHighlight(false);
            SetTurretLoadedHighlight(false);
        }
        else
        {
            var overTurretDrop = TurretLoadedSection.Visible &&
                                 _selectedTurret != null &&
                                 _infoMode is (InfoMode.Turret or InfoMode.TurretLoadedAmmo) &&
                                 (TurretLoadedSlot.GlobalRect.Contains(mouse.Position) ||
                                  TurretLoadedSection.GlobalRect.Contains(mouse.Position) ||
                                  InfoPanel.GlobalRect.Contains(mouse.Position));
            SetQuickUnloadHighlight(QuickUnloadPanel.GlobalRect.Contains(mouse.Position));
            SetStorageHighlight(false);
            SetTurretLoadedHighlight(overTurretDrop);
        }

        return true;
    }

    private void OnEndDrag()
    {
        _dragShadow.Visible = false;
        _dragShadow.SetPrototype(null);
        SetQuickUnloadHighlight(false);
        SetStorageHighlight(false);
        SetTurretLoadedHighlight(false);
    }

    private void SetQuickUnloadHighlight(bool active)
    {
        QuickUnloadPanel.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = active ? DropHighlight : PanelBg,
            BorderColor = active ? Accent : Color.FromHex("#334252"),
            BorderThickness = new Thickness(2),
        };
        for (var i = 0; i < _quickSlots.Count; i++) _quickSlots[i].PanelOverride = MakeSlotStyle(active && _quickQueue[i] == null);
    }

    private void SetStorageHighlight(bool active)
    {
        StoragePanel.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = active ? DropHighlight : PanelBg,
            BorderColor = active ? Accent : Color.FromHex("#334252"),
            BorderThickness = new Thickness(2),
        };
    }

    private void SetTurretLoadedHighlight(bool active)
    {
        var selected = _infoMode == InfoMode.TurretLoadedAmmo;
        _turretLoadedBg.PanelOverride = MakeSlotStyle(active || selected);
    }
}
