using System.Linq;
using System.Text;
using Content.Shared._Mono.PlantAnalyzer;
using Content.Shared.Atmos;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using FancyWindow = Content.Client.UserInterface.Controls.FancyWindow;

namespace Content.Client._Mono.PlantAnalyzer.UI;

[GenerateTypedNameReferences]
public sealed partial class PlantAnalyzerWindow : FancyWindow
{
    [Dependency] private readonly IEntityManager _entities = default!;
    private const string Indent = "\n   ";
    private PlantAnalyzerMode _mode;
    private PlantGeneId _gene;
    private int _databankIndex;
    private PlantGeneData[] _genes = [];
    private PlantGasData[] _consumedGases = [];
    private PlantGasData[] _exudedGases = [];
    private PlantChemicalData[] _chemicals = [];
    private bool _updatingTabs;
    private bool _updatingLists;

    public PlantAnalyzerWindow(PlantAnalyzerBoundUserInterface owner)
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        Tabs.OnTabChanged += _ =>
        {
            if (!_updatingTabs)
                owner.SetMode((PlantAnalyzerMode) Tabs.CurrentTab);
        };
        foreach (var gene in Enum.GetValues<PlantGeneId>())
            GeneList.AddItem(GeneName(gene));

        GeneList.OnItemSelected += args =>
        {
            if (!_updatingLists)
            {
                _gene = (PlantGeneId) args.ItemIndex;
                owner.SelectGene((PlantGeneId) args.ItemIndex);
            }
        };
        GeneDatabaseList.OnItemSelected += args => SelectDatabank(owner, args.ItemIndex, 0);
        ConsumeDatabaseList.OnItemSelected += args => SelectDatabank(owner, args.ItemIndex, _genes.Length);
        ExudeDatabaseList.OnItemSelected += args => SelectDatabank(owner, args.ItemIndex, _genes.Length + _consumedGases.Length);
        ChemicalDatabaseList.OnItemSelected += args => SelectDatabank(owner, args.ItemIndex, _genes.Length + _consumedGases.Length + _exudedGases.Length);
        DeleteDatabaseEntryButton.OnPressed += _ => owner.DeleteDatabankEntry();
    }

    public void Populate(PlantAnalyzerControlState state, bool applyMode, bool applyGene, bool applyDatabank)
    {
        if (applyGene)
            _gene = state.Gene;
        if (applyDatabank)
            _databankIndex = state.DatabankIndex;
        _genes = state.Genes;
        _consumedGases = state.ConsumedGases;
        _exudedGases = state.ExudedGases;
        _chemicals = state.Chemicals;
        if (applyMode)
            SetMode(state.Mode);
        UpdateControls();
    }

    public void SetMode(PlantAnalyzerMode mode)
    {
        _mode = mode;
        _updatingTabs = true;
        Tabs.CurrentTab = (int) mode;
        _updatingTabs = false;
    }

    private void SelectDatabank(PlantAnalyzerBoundUserInterface owner, int index, int offset)
    {
        if (!_updatingLists)
        {
            _databankIndex = index + offset;
            owner.SelectDatabankEntry(_databankIndex);
        }
    }

    private int DatabankCount => _genes.Length + _consumedGases.Length + _exudedGases.Length + _chemicals.Length;

    private void UpdateControls()
    {
        _updatingLists = true;
        GeneList[(int) _gene].Selected = true;

        GeneDatabaseList.Clear();
        foreach (var gene in _genes)
            GeneDatabaseList.AddItem(FormatGene(gene));

        ConsumeDatabaseList.Clear();
        foreach (var gas in _consumedGases)
            ConsumeDatabaseList.AddItem(Loc.GetString("plant-analyzer-database-consume-gas", ("gas", GasName(gas.Gas)), ("value", gas.Value)));

        ExudeDatabaseList.Clear();
        foreach (var gas in _exudedGases)
            ExudeDatabaseList.AddItem(Loc.GetString("plant-analyzer-database-exude-gas", ("gas", GasName(gas.Gas)), ("value", gas.Value)));

        ChemicalDatabaseList.Clear();
        foreach (var chemical in _chemicals)
        {
            var foreign = chemical.Quantity.Inherent ? "" : " [Foreign]";
            ChemicalDatabaseList.AddItem($"{chemical.Reagent}{foreign}: Min - {chemical.Quantity.Min}, Max - {chemical.Quantity.Max}, Potency Divisor - {chemical.Quantity.PotencyDivisor}");
        }

        if (_databankIndex < _genes.Length)
            GeneDatabaseList[_databankIndex].Selected = true;
        else if (_databankIndex < _genes.Length + _consumedGases.Length)
            ConsumeDatabaseList[_databankIndex - _genes.Length].Selected = true;
        else if (_databankIndex < _genes.Length + _consumedGases.Length + _exudedGases.Length)
            ExudeDatabaseList[_databankIndex - _genes.Length - _consumedGases.Length].Selected = true;
        else if (_databankIndex < DatabankCount)
        {
            var index = _databankIndex - _genes.Length - _consumedGases.Length - _exudedGases.Length;
            ChemicalDatabaseList[index].Selected = true;
        }

        _updatingLists = false;
    }

    private string FormatGene(PlantGeneData gene)
    {
        var name = GeneName(gene.Id);
        var value = gene.Id switch
        {
            PlantGeneId.Seedless or PlantGeneId.Viable or PlantGeneId.Ligneous or
                PlantGeneId.CanScream or PlantGeneId.TurnIntoKudzu => Loc.GetString(gene.Value == 0f
                    ? "plant-analyzer-boolean-false"
                    : "plant-analyzer-boolean-true"),
            PlantGeneId.HarvestRepeat => Loc.GetString($"plant-analyzer-harvest-{(int) gene.Value switch
            {
                0 => AnalyzerHarvestType.NoRepeat,
                1 => AnalyzerHarvestType.Repeat,
                2 => AnalyzerHarvestType.SelfHarvest,
                _ => AnalyzerHarvestType.Unknown
            }}"),
            PlantGeneId.Yield or PlantGeneId.GrowthStages => $"{(int) gene.Value}",
            _ => $"{gene.Value:F2}"
        };
        return $"{name}: {value}";
    }

    private static string GeneName(PlantGeneId gene)
        => gene switch
        {
            PlantGeneId.ConsumeGases => "Consume Gases",
            PlantGeneId.ExudeGases => "Exude Gases",
            PlantGeneId.Chemicals => "Chemical",
            _ => gene.ToString()
        };

    public void Populate(PlantAnalyzerScannedSeedPlantInformation msg)
    {
        var target = _entities.GetEntity(msg.TargetEntity);
        if (target == null)
        {
            NoData.Visible = true;
            ScanData.Visible = false;
            return;
        }

        NoData.Visible = false;
        ScanData.Visible = true;
        var chemicals = Join(msg.SeedChem ?? []);
        var consumed = GasNames(msg.ConsumeGases);
        var exuded = GasNames(msg.ExudeGases);
        var seedName = Loc.GetString(string.IsNullOrEmpty(msg.SeedName) ? "plant-analyzer-unknown-plant" : msg.SeedName);
        PlantName.Text = Loc.GetString(msg.IsTray
                ? "plant-analyzer-window-label-name-scanned-plant"
                : "plant-analyzer-window-label-name-scanned-seed",
            ("seedName", seedName));
        PlantYield.Text = Loc.GetString("plant-analyzer-plant-yield-text", ("seedYield", $"{msg.SeedYield:D0}"));
        Potency.Text = Loc.GetString("plant-analyzer-plant-potency-text", ("seedPotency", $"{msg.SeedPotency:F0}"));
        Repeat.Text = Loc.GetString("plant-analyzer-plant-harvest-text", ("plantHarvestType", Loc.GetString($"plant-analyzer-harvest-{msg.HarvestType}")));
        Endurance.Text = Loc.GetString("plant-analyzer-plant-endurance-text", ("seedEndurance", $"{msg.Endurance:F0}"));
        Lifespan.Text = Loc.GetString("plant-analyzer-plant-lifespan-text", ("lifespan", $"{msg.Lifespan:F1}"));
        Maturation.Text = Loc.GetString("plant-analyzer-plant-maturation-text", ("maturation", $"{msg.Maturation:F1}"));
        Production.Text = Loc.GetString("plant-analyzer-plant-production-text", ("production", $"{msg.Production:F1}"));
        GrowthStages.Text = Loc.GetString("plant-analyzer-plant-growthstages-text", ("growthStages", $"{msg.GrowthStages:D0}"));
        ConsumeGases.Text = Loc.GetString("plant-analyzer-plant-consume-text", ("gases", consumed));
        ExudeGases.Text = Loc.GetString("plant-analyzer-plant-exude-text", ("gases", exuded));
        Chemicals.Text = Loc.GetString("plant-analyzer-plant-chemistry-text", ("seedChem", chemicals));
        NutrientUsage.Text = Loc.GetString("plant-analyzer-tolerance-nutrient-usage", ("nutrientUsage", $"{msg.NutrientConsumption:F2}"));
        WaterUsage.Text = Loc.GetString("plant-analyzer-tolerance-water-usage", ("waterUsage", $"{msg.WaterConsumption:F2}"));
        IdealHeat.Text = Loc.GetString("plant-analyzer-tolerance-ideal-heat", ("idealHeat", $"{msg.IdealHeat:F0}"));
        HeatTolerance.Text = Loc.GetString("plant-analyzer-tolerance-heat-tolerance", ("heatTolerance", $"{msg.HeatTolerance:F1}"));
        IdealLight.Text = Loc.GetString("plant-analyzer-tolerance-ideal-light", ("idealLight", $"{msg.IdealLight:F1}"));
        LightTolerance.Text = Loc.GetString("plant-analyzer-tolerance-light-tolerance", ("lightTolerance", $"{msg.LightTolerance:F1}"));
        ToxinsTolerance.Text = Loc.GetString("plant-analyzer-tolerance-toxin-tolerance", ("toxinsTolerance", $"{msg.ToxinsTolerance:F1}"));
        LowPressureTolerance.Text = Loc.GetString("plant-analyzer-tolerance-low-pressure", ("lowPressureTolerance", $"{msg.LowPressureTolerance:F1}"));
        HighPressureTolerance.Text = Loc.GetString("plant-analyzer-tolerance-high-pressure", ("highPressureTolerance", $"{msg.HighPressureTolerance:F1}"));
        PestTolerance.Text = Loc.GetString("plant-analyzer-tolerance-pest-tolerance", ("pestTolerance", $"{msg.PestTolerance:F1}"));
        WeedTolerance.Text = Loc.GetString("plant-analyzer-tolerance-weed-tolerance", ("weedTolerance", $"{msg.WeedTolerance:F1}"));
        Traits.Text = Loc.GetString("plant-analyzer-plant-mutations-text", ("traits", MutationNames(msg.Mutations)));
        PlantSpeciation.Text = Loc.GetString("plant-analyzer-plant-speciation-text",
            ("speciation", Join((msg.Speciation ?? []).Select(name => Loc.GetString(name)))));
    }

    private string MutationNames(MutationFlags flags)
    {
        var names = new List<string>();
        if (flags.HasFlag(MutationFlags.TurnIntoKudzu)) names.Add(Loc.GetString("plant-analyzer-mutation-turnintokudzu"));
        if (flags.HasFlag(MutationFlags.Seedless)) names.Add(Loc.GetString("plant-analyzer-mutation-seedless"));
        if (flags.HasFlag(MutationFlags.Ligneous)) names.Add(Loc.GetString("plant-analyzer-mutation-ligneous"));
        if (flags.HasFlag(MutationFlags.CanScream)) names.Add(Loc.GetString("plant-analyzer-mutation-canscream"));
        if (flags.HasFlag(MutationFlags.Unviable)) names.Add(Loc.GetString("plant-analyzer-mutation-unviable"));
        return names.Count == 0 ? "-" : Join(names);
    }

    private string GasNames(GasFlags flags)
    {
        var names = new List<string>();
        foreach (Gas gas in Enum.GetValues(typeof(Gas)))
        {
            var flag = gas switch
            {
                Gas.Nitrogen => GasFlags.Nitrogen,
                Gas.Oxygen => GasFlags.Oxygen,
                Gas.CarbonDioxide => GasFlags.CarbonDioxide,
                Gas.Plasma => GasFlags.Plasma,
                Gas.Tritium => GasFlags.Tritium,
                Gas.WaterVapor => GasFlags.WaterVapor,
                Gas.Ammonia => GasFlags.Ammonia,
                Gas.NitrousOxide => GasFlags.NitrousOxide,
                Gas.Frezon => GasFlags.Frezon,
                _ => GasFlags.None
            };
            if (flag != GasFlags.None && flags.HasFlag(flag))
                names.Add(GasName(gas));
        }
        return names.Count == 0 ? Loc.GetString("plant-analyzer-plant-gases-none") : Join(names);
    }

    private string GasName(Gas gas)
        => Loc.GetString(gas switch
        {
            Gas.CarbonDioxide => "gases-co2",
            Gas.WaterVapor => "gases-water-vapor",
            Gas.NitrousOxide => "gases-n2o",
            _ => $"gases-{gas.ToString().ToLowerInvariant()}"
        });

    private static string Join(IEnumerable<string> values)
    {
        var result = new StringBuilder();
        foreach (var value in values)
            result.Append(Indent).Append(value);
        return result.Length == 0 ? "-" : result.ToString();
    }
}
